### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by N70** [N70/EUROPA#2]
- [x] Kerbals on EVA take resources from the pod, and put them back in when they get back in the pod  
- [] Kerbals who run out of an essential resource for a certain amount of time become KIA  
- [] Kerbals who become KIA during EVA are "frozen", similar to Kerbalism  
- [] Food rot  
- [] Food preservation units  
- [] Radiation and radiation belts  
- [] Food/water rations.
